openapi: 3.0.3
info:
  title: Dr Easy
  version: 1.0.0
servers:
  - url: https://localhost:8080
tags:
  - name: user
    description: Everything about users
  - name: file
    description: Everything about files
  - name: summar
    description: Everything about summars
paths:
  /user/auth:
    post:
      tags:
        - user
      summary: Authenticate an existing user
      description: Authenticate and existing user by email and password check
      operationId: authUser
      requestBody:
        description: Authenticate and existing user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/xml:
            schema:
              $ref: "#/components/schemas/User"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid email or password
        "404":
          description: User not found
        "422":
          description: Validation exception

components:
  schemas:
    User:
      required:
        - name
        - email
        - password
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: johndoe@dreasy.com.br
        password:
          type: string
          format: password
          example: 123456
      xml:
        name: user
