name: Dr.Easy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Check Python Install
        run: python --version

      - name: Check location
        run: ls -la

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Start venv
        run: |
          . /backend/dr_env/Scripts/activate
          pip install django
      #     pip install -r requirements.txt

      - name: Run tests
        run: |
          python backend/manage.py test
